// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5calU48mrGXeRtgkJicVqNZ_NJQknzr8',
    appId: '1:468746523537:web:289d58f02e62d136f3c030',
    messagingSenderId: '468746523537',
    projectId: 'task-47ffc',
    authDomain: 'task-47ffc.firebaseapp.com',
    storageBucket: 'task-47ffc.appspot.com',
    measurementId: 'G-3LYEEY0D6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTaiVImkZXudHf7JyW8eS15ztjxNAyoJU',
    appId: '1:468746523537:android:f64efff597bf1b80f3c030',
    messagingSenderId: '468746523537',
    projectId: 'task-47ffc',
    storageBucket: 'task-47ffc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYjL_2E_pWseeuRhGzR7rHq40oemFzn2A',
    appId: '1:468746523537:ios:19e5d88cf8f909b4f3c030',
    messagingSenderId: '468746523537',
    projectId: 'task-47ffc',
    storageBucket: 'task-47ffc.appspot.com',
    androidClientId: '468746523537-i4ttptvk8lrqdm4q4b1m01u0p5l90q64.apps.googleusercontent.com',
    iosClientId: '468746523537-eiqfobv7m9mfs297d5ub7k61h55i0d4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYjL_2E_pWseeuRhGzR7rHq40oemFzn2A',
    appId: '1:468746523537:ios:19e5d88cf8f909b4f3c030',
    messagingSenderId: '468746523537',
    projectId: 'task-47ffc',
    storageBucket: 'task-47ffc.appspot.com',
    androidClientId: '468746523537-i4ttptvk8lrqdm4q4b1m01u0p5l90q64.apps.googleusercontent.com',
    iosClientId: '468746523537-eiqfobv7m9mfs297d5ub7k61h55i0d4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5calU48mrGXeRtgkJicVqNZ_NJQknzr8',
    appId: '1:468746523537:web:6ab2f7da5eaaf6f8f3c030',
    messagingSenderId: '468746523537',
    projectId: 'task-47ffc',
    authDomain: 'task-47ffc.firebaseapp.com',
    storageBucket: 'task-47ffc.appspot.com',
    measurementId: 'G-2P22BKM377',
  );

}